services:

  client:
    build:
      context: client
    depends_on:
      - server.local
    volumes:
      - ./CA.pem:/usr/local/share/ca-certificates/CA.crt:ro

  server.local:
    image: nginx:latest
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./server/keys/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./server.local.key:/etc/ssl/private/server.key:ro
      - ./server.local.crt:/etc/ssl/certs/server.crt:ro
      - ./server/www:/app/www:ro

